# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01c91facbc685c1e4a48399e931f3cbd76797315ebc0ab046eab3142ab46128fd68485f9a3daa4e8c41a35afb28948a4422ba3b1bf775194b318c2e21747c14a

test:
  secret_key_base: 173df390bfc088efc988bf540ca1db437964ad9d7998428e440842bdd957961ce61e302744a7e77fa66acd74ea20cac519645e7a1645690a2d05a5ddb3e6e229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
